// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-redesign/CleanMinimal.tsx": () => import("../components/mockups/portfolio-redesign/CleanMinimal.tsx"),
  "./components/mockups/portfolio-redesign/DarkEditorial.tsx": () => import("../components/mockups/portfolio-redesign/DarkEditorial.tsx")
};
